[workspace]
members = ["core", "runtime", "structured-text", "iec", "iec-std", "wasm", "wasm-test"]

[patch.crates-io]
wasmer-runtime = { git = "https://github.com/wasmerio/wasmer", rev = "8a13917ec5b327d47b302c4002553d279536db54" }