[package]
name = "rustmatic"
version = "0.1.0"
authors = ["NOP0 <33583294+NOP0@users.noreply.github.com>", "Michael-F-Bryan <michaelfbryan@gmail.com>"]
edition = "2018"
description = "The entrypoint into the rustmatic runtime"
publish = false

[dependencies]
slotmap = "0.4.0"
rustmatic-runtime = { path = "./runtime" }
rustmatic-core = { path = "./core" }

[workspace]
members = ["core", "runtime"]